# Generated by Django 2.0.6 on 2018-06-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Flower',
        ),
    ]
